addr: ":8080"
cors: true
cors_config:
  allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allow_headers:
    - Origin
    - Content-Type
    - Authorization
  max_age: 43200
gateways:
  - prefix: "/api/v1"
    target: "http://example.com/api"
  - prefix: "/auth"
    target: "http://auth-service.com"
